Repository FEMessage/data-list, pull requests merged in 2019-08, with the labels that each got.

#39 chore: 更新 cli 配置
  package.json
  styleguide.config.js
  yarn.lock
Labels: chore

#56 fix: transform const keyword
  build/rollup.config.js
Labels: bug

#60 feat: 支持加载到底事件 complete
  src/data-list.vue
Labels: enhancement

#59 feat: 支持 slot=spinner
  docs/slot-spinner.md
  src/data-list.md
  src/data-list.vue
Labels: enhancement
