Repository FEMessage/data-list, pull requests merged in 2019-07, with the labels that each got.

#16 docs: add english readme
  README-en.md
Labels: enhancement

#33 chore(babel): 删除 absoluteRuntime 设置项
  .babelrc.js
Labels: chore

#37 fix: 修复getList有时会重复请求的问题
  package.json
  src/data-list.vue
  yarn.lock
Labels: bug

#38 docs: README弃用新浪图床使用语雀cdn
  README.md
Labels: documentation

#36 fix: 修复saveQuery=false时仍从url获取参数的bug
  package.json
  src/data-list.vue
  src/utils/query.js
  yarn.lock
Labels: bug

#40 docs: update README badges & contributing
  .github/badge.yml
  .grenrc.js
  .stylelintrc
  .travis.yml
  README-en.md
  README.md
  notify.sh
  package.json
Labels: documentation
